name: 🙋 Feature Request
description: Want to add a feature to react-spectrum-charts?
body:
  - type: markdown
    attributes:
      value: '### Thanks for filing an issue! Before you submit, search open/closed issues before submitting since someone might have asked the same thing before!'
  - type: markdown
    attributes:
      value: '# 🙋 Feature Request'
  - type: textarea
    id: general-summary
    attributes:
      label: Provide a general summary of the feature here
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: 🤔 Expected Behavior?
      description: Tell us how the feature should work!
    validations:
      required: true
  - type: textarea
    id: possible-solution
    attributes:
      label: 💁 Possible Solution
      description: Ideas how to implement this feature or a similar solution/workaround that already exists
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: 🔦 Context
      description: |
        Providing context helps us come up with a solution that is most useful in the real world.
        What are we trying to accomplish with this feature?
    validations:
      required: true
  - type: textarea
    id: examples
    attributes:
      label: 💻 Examples
      description: Examples help us understand the requested feature better. Include design mocks here if possible.
  - type: markdown
    attributes:
      value: '## 🦄 Other'
  - type: input
    id: company-team
    attributes:
      label: 🧢 Your Company/Team
      description: Which team is requesting this feature? (i.e. Adobe/Photoshop)
