name: 📝 Feedback
description: Have some feedback?
body:
  - type: markdown
    attributes:
      value: '### Thanks for filing an issue! Before you submit, search open/closed issues before submitting since someone might have asked the same thing before!'
  - type: markdown
    attributes:
      value: '# 📝 Feedback'
  - type: textarea
    attributes:
      label: Provide your feedback here.
    validations:
      required: true
