#!/usr/bin/env node
/*
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

/* eslint-disable @typescript-eslint/no-var-requires */
const fs = require('fs');
const path = require('path');

const DESIGN_TOKENS_DIST = path.join(__dirname, '../packages/mcp/dist/src/designTokens.js');
const SKILL_PATH = path.join(__dirname, '../llm/skills/s2-design-tokens/SKILL.md');
const SKILL_DIR = path.dirname(SKILL_PATH);

/**
 * Loads the compiled design token catalog, the same data served by the
 * list_design_tokens/read_design_tokens MCP tools in @spectrum-charts/mcp.
 * @returns {Array<{id: string, title: string, description: string, tokens: object}>}
 */
function loadDesignTokenCategories() {
  if (!fs.existsSync(DESIGN_TOKENS_DIST)) {
    throw new Error(
      `Compiled design tokens not found at ${DESIGN_TOKENS_DIST}.\n` +
        "Run 'yarn workspace @spectrum-charts/mcp build' first."
    );
  }
  // eslint-disable-next-line global-require, import/no-dynamic-require
  const mod = require(DESIGN_TOKENS_DIST);
  return mod.DESIGN_TOKEN_CATEGORIES;
}

/**
 * Renders the "colors" category as a light/dark hex lookup table.
 * @param {object} tokens - The colors category's `tokens` object
 * @returns {string}
 */
function renderColorsSection(tokens) {
  const { scales, categorical, defaultFontColorToken } = tokens;
  let md = '';

  md += `Default font color token: \`${defaultFontColorToken}\`\n\n`;

  md += '### Color Scale (token name → hex, by color scheme)\n\n';
  md += '| Token | Light | Dark |\n|---|---|---|\n';
  const tokenNames = Object.keys(scales.light);
  for (const name of tokenNames) {
    md += `| \`${name}\` | ${scales.light[name]} | ${scales.dark[name] ?? ''} |\n`;
  }
  md += '\n';

  md += '### Categorical Palettes\n\n';
  for (const [paletteName, colors] of Object.entries(categorical)) {
    md += `- \`${paletteName}\`: ${colors.map((c) => `\`${c}\``).join(', ')}\n`;
  }
  md += '\n';

  return md;
}

/**
 * Renders a plain nested-object token category (typography, spacing) as a bullet list,
 * recursing into nested objects without assuming specific field names.
 * @param {object} value
 * @param {number} depth
 * @returns {string}
 */
function renderNestedTokens(value, depth = 0) {
  let md = '';
  const indent = '  '.repeat(depth);
  for (const [key, val] of Object.entries(value)) {
    if (val !== null && typeof val === 'object' && !Array.isArray(val)) {
      md += `${indent}- **${key}**:\n`;
      md += renderNestedTokens(val, depth + 1);
    } else {
      md += `${indent}- **${key}**: \`${JSON.stringify(val)}\`\n`;
    }
  }
  return md;
}

/**
 * Renders one design token category as a markdown section.
 * @param {{id: string, title: string, description: string, tokens: object}} category
 * @returns {string}
 */
function renderCategory(category) {
  let md = `## ${category.title}\n\n${category.description}\n\n`;
  md += category.id === 'colors' ? renderColorsSection(category.tokens) : renderNestedTokens(category.tokens);
  return md;
}

/**
 * Builds the full SKILL.md content from the design token catalog.
 * @param {Array<{id: string, title: string, description: string, tokens: object}>} categories
 * @returns {string}
 */
function generateSkillContent(categories) {
  const sections = categories.map(renderCategory).join('\n');

  return `---
name: s2-design-tokens
description: Canonical Spectrum 2 design tokens (colors, typography, spacing) for React Spectrum Charts. Use whenever generating or styling a chart so colors/fonts/spacing match real Spectrum 2 values instead of invented ones.
---

# Spectrum 2 Design Tokens

*Auto-generated by \`scripts/createDesignTokenSkill.js\` from \`packages/mcp/src/designTokens.ts\` — do not hand-edit. Regenerate with \`yarn skills:update-s2-design-tokens\` after changing the source catalog.*

*Generated on: ${new Date().toISOString()}*

This is the same data served by the \`list_design_tokens\`/\`read_design_tokens\` tools in \`@spectrum-charts/mcp\`. When generating a chart spec (for RSC, Vega, Chart.js, or D3), only use color/font/spacing values that appear below — never invent a hex value, font size, or spacing number that isn't listed here.

${sections}
`;
}

function main() {
  const categories = loadDesignTokenCategories();
  const content = generateSkillContent(categories);

  fs.mkdirSync(SKILL_DIR, { recursive: true });
  fs.writeFileSync(SKILL_PATH, content, 'utf-8');
  console.log(`✅ Updated design token skill at: ${SKILL_PATH}`);
}

if (require.main === module) {
  main();
}

module.exports = { loadDesignTokenCategories, generateSkillContent };
