#!/usr/bin/env node
/*
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

/* eslint-disable @typescript-eslint/no-var-requires */
const fs = require('fs');
const path = require('path');

const FEATURE_CATALOG_DIST = path.join(__dirname, '../packages/mcp/dist/src/featureCatalog.js');
const SKILL_PATH = path.join(__dirname, '../llm/skills/chart-features/SKILL.md');
const SKILL_DIR = path.dirname(SKILL_PATH);

const CATEGORY_TITLES = {
  mark: 'Marks (top-level chart types)',
  decoration: 'Mark decorations / sub-features',
  'chart-level': 'Chart-level / shared features',
};

/**
 * Loads the compiled chart feature catalog, the same data served by the
 * list_chart_features/read_chart_feature MCP tools in @spectrum-charts/mcp.
 * @returns {Array<object>}
 */
function loadChartFeatures() {
  if (!fs.existsSync(FEATURE_CATALOG_DIST)) {
    throw new Error(
      `Compiled feature catalog not found at ${FEATURE_CATALOG_DIST}.\n` +
        "Run 'yarn workspace @spectrum-charts/mcp build' first."
    );
  }
  // eslint-disable-next-line global-require, import/no-dynamic-require
  const mod = require(FEATURE_CATALOG_DIST);
  return mod.CHART_FEATURE_CATALOG;
}

/**
 * Renders one chart feature as a markdown entry.
 * @param {object} feature
 * @returns {string}
 */
function renderFeature(feature) {
  let md = `### ${feature.name} (\`${feature.id}\`)\n\n`;
  md += `${feature.description}\n\n`;
  md += `- **Applies to**: ${feature.appliesTo.map((a) => `\`${a}\``).join(', ')}\n`;
  md += `- **Related tokens**: ${
    feature.relatedTokens.length ? feature.relatedTokens.map((t) => `\`${t}\``).join(', ') : '_none_'
  }\n`;
  md += `- **RSC support**: S1 ${feature.rscSupport.s1 ? '✅' : '❌'}, S2 ${feature.rscSupport.s2 ? '✅' : '❌'}\n`;
  if (feature.rscSupport.s1Maturity || feature.rscSupport.s2Maturity) {
    const parts = [];
    if (feature.rscSupport.s1Maturity) parts.push(`S1 via \`${feature.rscSupport.s1Maturity}\` import path`);
    if (feature.rscSupport.s2Maturity) parts.push(`S2 via \`${feature.rscSupport.s2Maturity}\` import path`);
    md += `- **Maturity**: ${parts.join(', ')} — not yet in the stable barrel, but alpha/rc components are considered supported\n`;
  }
  md += `- **Canonical parameter shape**: \`${feature.optionsType.typeName}\` in \`${feature.optionsType.filePath}\`\n`;
  if (feature.builderFile) {
    md += `- **Builder implementation**: \`${feature.builderFile}\`\n`;
  }
  md += '\n';
  return md;
}

/**
 * Groups features by category and renders each group as a section, in a fixed category order.
 * @param {Array<object>} features
 * @returns {string}
 */
function renderCategories(features) {
  let md = '';
  for (const [category, title] of Object.entries(CATEGORY_TITLES)) {
    const inCategory = features.filter((f) => f.category === category);
    if (inCategory.length === 0) continue;
    md += `## ${title}\n\n`;
    md += inCategory.map(renderFeature).join('');
  }
  return md;
}

/**
 * Builds the full SKILL.md content from the chart feature catalog.
 * @param {Array<object>} features
 * @returns {string}
 */
function generateSkillContent(features) {
  const sections = renderCategories(features);

  return `---
name: chart-features
description: Engine-agnostic catalog of every chart feature React Spectrum Charts implements (marks, decorations, chart-level features). Use when generating a chart spec for RSC, Vega, Chart.js, or D3 to confirm a requested feature exists and what it's configured with, before inventing behavior.
---

# RSC Chart Feature Catalog

*Auto-generated by \`scripts/createChartFeatureSkill.js\` from \`packages/mcp/src/featureCatalog.ts\` — do not hand-edit. Regenerate with \`yarn skills:update-chart-features\` after changing the source catalog.*

*Generated on: ${new Date().toISOString()}*

This is the same data served by the \`list_chart_features\`/\`read_chart_feature\` tools in \`@spectrum-charts/mcp\`. Parameter shapes are intentionally not transcribed here — each feature points at its canonical \`*Options\` TypeScript type instead, so this catalog can't drift from the real source. "RSC support" reflects whether a JSX wrapper component exists today, including alpha/rc import paths (\`@adobe/react-spectrum-charts/alpha\` or \`/rc\`) — those are considered supported, just not yet in the stable barrel; a feature with no RSC component at all is still a real, spec-buildable feature for the Vega/Chart.js/D3 fallback path.

${sections}
`;
}

function main() {
  const features = loadChartFeatures();
  const content = generateSkillContent(features);

  fs.mkdirSync(SKILL_DIR, { recursive: true });
  fs.writeFileSync(SKILL_PATH, content, 'utf-8');
  console.log(`✅ Updated chart feature skill at: ${SKILL_PATH}`);
}

if (require.main === module) {
  main();
}

module.exports = { loadChartFeatures, generateSkillContent };
